### ISSUE TITLE
Xs and Os look odd

### ISSUE THREAD

**Issue by HaoMinh** [caktus/ultimatetictactoe#36]
Appears to be repeating and layering on top of itself when on a large screen. a problem with the transform scale. 

Resolution: fix it for the tradeshow monitor

**Comment by HaoMinh** [comment]
Trevor found the solution:
.slot.x .symbol {
background-repeat: no-repeat;
}

Calvin says this is a chrome bug

**Comment by rayt86** [comment]
This problem looks to be solved already.

**Comment by rayt86** [comment]
I was wrong. there are still instances of this happening.

**Comment by rayt86** [comment]
PR is in for this issue.
