### ISSUE TITLE
User can tap an the opponent's occupied space on a mini-board and temporarily freeze the game

### ISSUE THREAD

**Issue by ncnwoko** [caktus/ultimatetictactoe#61]
![bug-tic-tac-toe_occupiedspace](https://cloud.githubusercontent.com/assets/5464067/9658435/54b72574-5217-11e5-8513-20e6dacd4237.JPG)

**Comment by ironfroggy** [comment]
i see your problem right there.

you got your monitor upsidedown.

**Comment by ncnwoko** [comment]
Confirmed fix resolved this issue
